package com.sunday.wkday.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table wk_op_log
 */
public class WkOpLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_op_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_op_log.op_user_id
     *
     * @mbg.generated
     */
    private String opUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_op_log.project_no
     *
     * @mbg.generated
     */
    private String projectNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_op_log.record_no
     *
     * @mbg.generated
     */
    private String recordNo;

    /**
     * Database Column Remarks:
     *   1新增 2修改 3删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_op_log.op_type
     *
     * @mbg.generated
     */
    private Byte opType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_op_log.detail
     *
     * @mbg.generated
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_op_log.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_op_log
     *
     * @mbg.generated
     */
    public WkOpLog(Long id, String opUserId, String projectNo, String recordNo, Byte opType, String detail, Date createTime) {
        this.id = id;
        this.opUserId = opUserId;
        this.projectNo = projectNo;
        this.recordNo = recordNo;
        this.opType = opType;
        this.detail = detail;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_op_log
     *
     * @mbg.generated
     */
    public WkOpLog() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_op_log.id
     *
     * @return the value of wk_op_log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_op_log.id
     *
     * @param id the value for wk_op_log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_op_log.op_user_id
     *
     * @return the value of wk_op_log.op_user_id
     *
     * @mbg.generated
     */
    public String getOpUserId() {
        return opUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_op_log.op_user_id
     *
     * @param opUserId the value for wk_op_log.op_user_id
     *
     * @mbg.generated
     */
    public void setOpUserId(String opUserId) {
        this.opUserId = opUserId == null ? null : opUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_op_log.project_no
     *
     * @return the value of wk_op_log.project_no
     *
     * @mbg.generated
     */
    public String getProjectNo() {
        return projectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_op_log.project_no
     *
     * @param projectNo the value for wk_op_log.project_no
     *
     * @mbg.generated
     */
    public void setProjectNo(String projectNo) {
        this.projectNo = projectNo == null ? null : projectNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_op_log.record_no
     *
     * @return the value of wk_op_log.record_no
     *
     * @mbg.generated
     */
    public String getRecordNo() {
        return recordNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_op_log.record_no
     *
     * @param recordNo the value for wk_op_log.record_no
     *
     * @mbg.generated
     */
    public void setRecordNo(String recordNo) {
        this.recordNo = recordNo == null ? null : recordNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_op_log.op_type
     *
     * @return the value of wk_op_log.op_type
     *
     * @mbg.generated
     */
    public Byte getOpType() {
        return opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_op_log.op_type
     *
     * @param opType the value for wk_op_log.op_type
     *
     * @mbg.generated
     */
    public void setOpType(Byte opType) {
        this.opType = opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_op_log.detail
     *
     * @return the value of wk_op_log.detail
     *
     * @mbg.generated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_op_log.detail
     *
     * @param detail the value for wk_op_log.detail
     *
     * @mbg.generated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_op_log.create_time
     *
     * @return the value of wk_op_log.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_op_log.create_time
     *
     * @param createTime the value for wk_op_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}