package com.sunday.wkday.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table wk_project
 */
public class WkProject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_project.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_project.project_no
     *
     * @mbg.generated
     */
    private String projectNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_project.project_name
     *
     * @mbg.generated
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_project.project_admin
     *
     * @mbg.generated
     */
    private String projectAdmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_project.sub_admin
     *
     * @mbg.generated
     */
    private String subAdmin;

    /**
     * Database Column Remarks:
     *   1正常 -1关闭
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_project.project_status
     *
     * @mbg.generated
     */
    private Byte projectStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_project.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_project
     *
     * @mbg.generated
     */
    public WkProject(Long id, String projectNo, String projectName, String projectAdmin, String subAdmin, Byte projectStatus, Date createTime) {
        this.id = id;
        this.projectNo = projectNo;
        this.projectName = projectName;
        this.projectAdmin = projectAdmin;
        this.subAdmin = subAdmin;
        this.projectStatus = projectStatus;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_project
     *
     * @mbg.generated
     */
    public WkProject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_project.id
     *
     * @return the value of wk_project.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_project.id
     *
     * @param id the value for wk_project.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_project.project_no
     *
     * @return the value of wk_project.project_no
     *
     * @mbg.generated
     */
    public String getProjectNo() {
        return projectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_project.project_no
     *
     * @param projectNo the value for wk_project.project_no
     *
     * @mbg.generated
     */
    public void setProjectNo(String projectNo) {
        this.projectNo = projectNo == null ? null : projectNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_project.project_name
     *
     * @return the value of wk_project.project_name
     *
     * @mbg.generated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_project.project_name
     *
     * @param projectName the value for wk_project.project_name
     *
     * @mbg.generated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_project.project_admin
     *
     * @return the value of wk_project.project_admin
     *
     * @mbg.generated
     */
    public String getProjectAdmin() {
        return projectAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_project.project_admin
     *
     * @param projectAdmin the value for wk_project.project_admin
     *
     * @mbg.generated
     */
    public void setProjectAdmin(String projectAdmin) {
        this.projectAdmin = projectAdmin == null ? null : projectAdmin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_project.sub_admin
     *
     * @return the value of wk_project.sub_admin
     *
     * @mbg.generated
     */
    public String getSubAdmin() {
        return subAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_project.sub_admin
     *
     * @param subAdmin the value for wk_project.sub_admin
     *
     * @mbg.generated
     */
    public void setSubAdmin(String subAdmin) {
        this.subAdmin = subAdmin == null ? null : subAdmin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_project.project_status
     *
     * @return the value of wk_project.project_status
     *
     * @mbg.generated
     */
    public Byte getProjectStatus() {
        return projectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_project.project_status
     *
     * @param projectStatus the value for wk_project.project_status
     *
     * @mbg.generated
     */
    public void setProjectStatus(Byte projectStatus) {
        this.projectStatus = projectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_project.create_time
     *
     * @return the value of wk_project.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_project.create_time
     *
     * @param createTime the value for wk_project.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}