package com.sunday.wkday.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table wk_record
 */
public class WkRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_record.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_record.project_no
     *
     * @mbg.generated
     */
    private String projectNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_record.record_no
     *
     * @mbg.generated
     */
    private String recordNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_record.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_record.wk_hour
     *
     * @mbg.generated
     */
    private BigDecimal wkHour;

    /**
     * Database Column Remarks:
     *   工作天
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_record.wk_date
     *
     * @mbg.generated
     */
    private String wkDate;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_record.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   操作人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_record.op_user_id
     *
     * @mbg.generated
     */
    private String opUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_record.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_record.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_record
     *
     * @mbg.generated
     */
    public WkRecord(Long id, String projectNo, String recordNo, String userId, BigDecimal wkHour, String wkDate, String remark, String opUserId, Date createTime, Date updateTime) {
        this.id = id;
        this.projectNo = projectNo;
        this.recordNo = recordNo;
        this.userId = userId;
        this.wkHour = wkHour;
        this.wkDate = wkDate;
        this.remark = remark;
        this.opUserId = opUserId;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_record
     *
     * @mbg.generated
     */
    public WkRecord() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_record.id
     *
     * @return the value of wk_record.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_record.id
     *
     * @param id the value for wk_record.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_record.project_no
     *
     * @return the value of wk_record.project_no
     *
     * @mbg.generated
     */
    public String getProjectNo() {
        return projectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_record.project_no
     *
     * @param projectNo the value for wk_record.project_no
     *
     * @mbg.generated
     */
    public void setProjectNo(String projectNo) {
        this.projectNo = projectNo == null ? null : projectNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_record.record_no
     *
     * @return the value of wk_record.record_no
     *
     * @mbg.generated
     */
    public String getRecordNo() {
        return recordNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_record.record_no
     *
     * @param recordNo the value for wk_record.record_no
     *
     * @mbg.generated
     */
    public void setRecordNo(String recordNo) {
        this.recordNo = recordNo == null ? null : recordNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_record.user_id
     *
     * @return the value of wk_record.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_record.user_id
     *
     * @param userId the value for wk_record.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_record.wk_hour
     *
     * @return the value of wk_record.wk_hour
     *
     * @mbg.generated
     */
    public BigDecimal getWkHour() {
        return wkHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_record.wk_hour
     *
     * @param wkHour the value for wk_record.wk_hour
     *
     * @mbg.generated
     */
    public void setWkHour(BigDecimal wkHour) {
        this.wkHour = wkHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_record.wk_date
     *
     * @return the value of wk_record.wk_date
     *
     * @mbg.generated
     */
    public String getWkDate() {
        return wkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_record.wk_date
     *
     * @param wkDate the value for wk_record.wk_date
     *
     * @mbg.generated
     */
    public void setWkDate(String wkDate) {
        this.wkDate = wkDate == null ? null : wkDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_record.remark
     *
     * @return the value of wk_record.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_record.remark
     *
     * @param remark the value for wk_record.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_record.op_user_id
     *
     * @return the value of wk_record.op_user_id
     *
     * @mbg.generated
     */
    public String getOpUserId() {
        return opUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_record.op_user_id
     *
     * @param opUserId the value for wk_record.op_user_id
     *
     * @mbg.generated
     */
    public void setOpUserId(String opUserId) {
        this.opUserId = opUserId == null ? null : opUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_record.create_time
     *
     * @return the value of wk_record.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_record.create_time
     *
     * @param createTime the value for wk_record.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_record.update_time
     *
     * @return the value of wk_record.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_record.update_time
     *
     * @param updateTime the value for wk_record.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}