package com.sunday.wkday.dao;

import com.sunday.wkday.entity.WkDiary;
import com.sunday.wkday.entity.WkDiaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WkDiaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_diary
     *
     * @mbg.generated
     */
    long countByExample(WkDiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_diary
     *
     * @mbg.generated
     */
    int deleteByExample(WkDiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_diary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_diary
     *
     * @mbg.generated
     */
    int insert(WkDiary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_diary
     *
     * @mbg.generated
     */
    int insertSelective(WkDiary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_diary
     *
     * @mbg.generated
     */
    List<WkDiary> selectByExample(WkDiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_diary
     *
     * @mbg.generated
     */
    WkDiary selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_diary
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WkDiary record, @Param("example") WkDiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_diary
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WkDiary record, @Param("example") WkDiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_diary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WkDiary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_diary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WkDiary record);
}