package com.sunday.wkday.dao;

import com.sunday.wkday.entity.WkMember;
import com.sunday.wkday.entity.WkMemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WkMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_member
     *
     * @mbg.generated
     */
    long countByExample(WkMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_member
     *
     * @mbg.generated
     */
    int deleteByExample(WkMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_member
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_member
     *
     * @mbg.generated
     */
    int insert(WkMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_member
     *
     * @mbg.generated
     */
    int insertSelective(WkMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_member
     *
     * @mbg.generated
     */
    List<WkMember> selectByExample(WkMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_member
     *
     * @mbg.generated
     */
    WkMember selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_member
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WkMember record, @Param("example") WkMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_member
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WkMember record, @Param("example") WkMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_member
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WkMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_member
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WkMember record);
}