package com.sunday.wkday.dao;

import com.sunday.wkday.entity.WkOpLog;
import com.sunday.wkday.entity.WkOpLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WkOpLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_op_log
     *
     * @mbg.generated
     */
    long countByExample(WkOpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_op_log
     *
     * @mbg.generated
     */
    int deleteByExample(WkOpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_op_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_op_log
     *
     * @mbg.generated
     */
    int insert(WkOpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_op_log
     *
     * @mbg.generated
     */
    int insertSelective(WkOpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_op_log
     *
     * @mbg.generated
     */
    List<WkOpLog> selectByExample(WkOpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_op_log
     *
     * @mbg.generated
     */
    WkOpLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_op_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WkOpLog record, @Param("example") WkOpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_op_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WkOpLog record, @Param("example") WkOpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_op_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WkOpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_op_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WkOpLog record);
}