package com.sunday.wkday.dao;

import com.sunday.wkday.entity.WkProject;
import com.sunday.wkday.entity.WkProjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WkProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_project
     *
     * @mbg.generated
     */
    long countByExample(WkProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_project
     *
     * @mbg.generated
     */
    int deleteByExample(WkProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_project
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_project
     *
     * @mbg.generated
     */
    int insert(WkProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_project
     *
     * @mbg.generated
     */
    int insertSelective(WkProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_project
     *
     * @mbg.generated
     */
    List<WkProject> selectByExample(WkProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_project
     *
     * @mbg.generated
     */
    WkProject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_project
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WkProject record, @Param("example") WkProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_project
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WkProject record, @Param("example") WkProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_project
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WkProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_project
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WkProject record);
}