package com.sunday.wkday.dao;

import com.sunday.wkday.entity.WkUser;
import com.sunday.wkday.entity.WkUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WkUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_user
     *
     * @mbg.generated
     */
    long countByExample(WkUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_user
     *
     * @mbg.generated
     */
    int deleteByExample(WkUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_user
     *
     * @mbg.generated
     */
    int insert(WkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_user
     *
     * @mbg.generated
     */
    int insertSelective(WkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_user
     *
     * @mbg.generated
     */
    List<WkUser> selectByExample(WkUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_user
     *
     * @mbg.generated
     */
    WkUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WkUser record, @Param("example") WkUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WkUser record, @Param("example") WkUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WkUser record);
}